// Mock data for Agent Orchestrator

const AGENTS = [
  {
    id: "agt_4f2e9c",
    name: "frontend-refactor",
    status: "running",
    model: "Sonnet 4.5",
    workspace: "/work/checkout-ui",
    cpu: 24,
    mem: 412,
    uptime: 4280, // seconds
    msgsIn: 7,
    msgsOut: 12,
    unread: 2,
    systemPrompt: "You are a senior frontend engineer refactoring the checkout flow. Prefer small, surgical commits. Always run tests before reporting back.",
    image: "claude-agent:1.4.2",
  },
  {
    id: "agt_8a1b03",
    name: "test-writer",
    status: "running",
    model: "Sonnet 4.5",
    workspace: "/work/api-server",
    cpu: 8,
    mem: 268,
    uptime: 11820,
    msgsIn: 3,
    msgsOut: 18,
    unread: 1,
    systemPrompt: "Write integration tests for any new endpoints. Coordinate with the backend agent before implementing.",
    image: "claude-agent:1.4.2",
  },
  {
    id: "agt_2d77f1",
    name: "docs-keeper",
    status: "idle",
    model: "Haiku 4.5",
    workspace: "/work/api-server",
    cpu: 0,
    mem: 84,
    uptime: 27640,
    msgsIn: 14,
    msgsOut: 9,
    unread: 0,
    systemPrompt: "Keep README, CHANGELOG, and inline docs accurate. React when other agents post 'docs-needed' messages.",
    image: "claude-agent:1.4.2",
  },
  {
    id: "agt_9b3a45",
    name: "backend-api",
    status: "running",
    model: "Opus 4",
    workspace: "/work/api-server",
    cpu: 41,
    mem: 824,
    uptime: 9120,
    msgsIn: 22,
    msgsOut: 14,
    unread: 4,
    systemPrompt: "Implement and maintain the REST API. Coordinate schema changes with frontend-refactor and test-writer.",
    image: "claude-agent:1.4.2",
  },
  {
    id: "agt_7e0c12",
    name: "release-pilot",
    status: "starting",
    model: "Sonnet 4.5",
    workspace: "/work/release-tools",
    cpu: 0,
    mem: 0,
    uptime: 8,
    msgsIn: 0,
    msgsOut: 0,
    unread: 0,
    systemPrompt: "Drive release branches: cut, tag, draft notes, ping reviewers.",
    image: "claude-agent:1.4.2",
  },
  {
    id: "agt_5f88de",
    name: "perf-investigator",
    status: "error",
    model: "Sonnet 4.5",
    workspace: "/work/checkout-ui",
    cpu: 0,
    mem: 0,
    uptime: 0,
    msgsIn: 1,
    msgsOut: 0,
    unread: 1,
    systemPrompt: "Profile the checkout flow. Find regressions over the last 7 commits.",
    image: "claude-agent:1.4.2",
    errorMsg: "Container exited (1): rate_limit_exceeded",
  },
  {
    id: "agt_1c4408",
    name: "schema-migrator",
    status: "stopped",
    model: "Haiku 4.5",
    workspace: "/work/api-server",
    cpu: 0,
    mem: 0,
    uptime: 0,
    msgsIn: 0,
    msgsOut: 6,
    unread: 0,
    systemPrompt: "Apply pending Alembic migrations. Verify rollback works.",
    image: "claude-agent:1.4.2",
  },
  {
    id: "agt_6e220a",
    name: "ui-reviewer",
    status: "idle",
    model: "Sonnet 4.5",
    workspace: "/work/checkout-ui",
    cpu: 1,
    mem: 132,
    uptime: 18230,
    msgsIn: 5,
    msgsOut: 7,
    unread: 0,
    systemPrompt: "Visually review every PR from frontend-refactor. Flag accessibility issues.",
    image: "claude-agent:1.4.2",
  },
];

// Inbox messages for the active agent (frontend-refactor)
const INBOX = [
  {
    id: "msg_a72f1",
    from: "backend-api",
    to: "frontend-refactor",
    direction: "in",
    subject: "Schema change: /api/checkout/session",
    type: "task",
    unread: true,
    time: "2m",
    fullTime: "11:42:08",
    preview: '{"action":"schema_update","path":"/api/checkout/session","fields":["promo_code","tax_region"]}',
    body: {
      action: "schema_update",
      path: "/api/checkout/session",
      method: "POST",
      changes: {
        added: ["promo_code", "tax_region"],
        removed: [],
        modified: [
          { field: "total", from: "integer", to: "decimal" }
        ]
      },
      breaking: true,
      coordinate_with: ["test-writer", "ui-reviewer"],
      target_branch: "feat/checkout-v3",
      due: "2026-05-05T18:00:00Z"
    },
  },
  {
    id: "msg_b91c4",
    from: "ui-reviewer",
    to: "frontend-refactor",
    direction: "in",
    subject: "A11y findings on PaymentStep",
    type: "report",
    unread: true,
    time: "14m",
    fullTime: "11:30:21",
    preview: '{"violations":3,"severity":"moderate","wcag":"2.1 AA"}',
    body: {
      component: "PaymentStep",
      file: "src/checkout/PaymentStep.tsx",
      violations: [
        { rule: "label-has-associated-control", line: 87, severity: "serious" },
        { rule: "color-contrast", line: 142, ratio: 3.8, required: 4.5, severity: "moderate" },
        { rule: "aria-required-attr", line: 201, severity: "moderate" }
      ],
      wcag: "2.1 AA",
      suggested_fix_branch: "fix/payment-step-a11y"
    },
  },
  {
    id: "msg_c33ee",
    from: "test-writer",
    to: "frontend-refactor",
    direction: "in",
    subject: "Need fixtures for new promo flow",
    type: "query",
    unread: false,
    time: "38m",
    fullTime: "11:06:54",
    preview: '{"requesting":"fixtures","scope":"promo_code_validation"}',
    body: {
      requesting: "fixtures",
      scope: "promo_code_validation",
      cases: ["valid_active", "valid_expired", "invalid_format", "rate_limited"],
      format: "json",
      target_dir: "tests/fixtures/promo/"
    },
  },
  {
    id: "msg_d51a2",
    from: "docs-keeper",
    to: "frontend-refactor",
    direction: "in",
    subject: "CHANGELOG entry pending review",
    type: "task",
    unread: false,
    time: "1h",
    fullTime: "10:31:02",
    preview: '{"file":"CHANGELOG.md","section":"Unreleased","action":"review"}',
    body: {
      file: "CHANGELOG.md",
      section: "Unreleased",
      diff_url: "/diff/changelog/c8a3f",
      action: "review"
    },
  },
  {
    id: "msg_e0782",
    from: "backend-api",
    to: "frontend-refactor",
    direction: "in",
    subject: "Rate limit headers added",
    type: "report",
    unread: false,
    time: "2h",
    fullTime: "09:48:11",
    preview: '{"headers":["X-RateLimit-Remaining","X-RateLimit-Reset"]}',
    body: {
      headers_added: ["X-RateLimit-Remaining", "X-RateLimit-Reset", "Retry-After"],
      affects: ["/api/checkout/*", "/api/promo/*"],
      backwards_compatible: true
    },
  },
  {
    id: "msg_f9931",
    from: "release-pilot",
    to: "frontend-refactor",
    direction: "in",
    subject: "v3.4.0 release window",
    type: "alert",
    unread: false,
    time: "3h",
    fullTime: "08:55:30",
    preview: '{"window":"2026-05-06T14:00:00Z","freeze":"2026-05-06T12:00:00Z"}',
    body: {
      release_tag: "v3.4.0",
      freeze: "2026-05-06T12:00:00Z",
      window: "2026-05-06T14:00:00Z",
      required_from: ["frontend-refactor", "backend-api"]
    },
  },
];

// Live log lines (will keep streaming in)
const LOG_SEED = [
  { t: "11:42:14", lvl: "system", msg: 'container <span class="hl-kw">started</span> <span class="hl-dim">image=claude-agent:1.4.2 workspace=/work/checkout-ui</span>' },
  { t: "11:42:14", lvl: "system", msg: 'mounted <span class="hl-path">~/.claude</span> from secrets store <span class="hl-dim">(encrypted, sha256=8a3f…c1)</span>' },
  { t: "11:42:15", lvl: "system", msg: 'inbox watcher attached <span class="hl-path">/agent/inbox/</span>' },
  { type: "divider", msg: "Session resumed" },
  { t: "11:42:16", lvl: "claude", msg: 'Reading message from <span class="hl-kw">backend-api</span>: schema change for <span class="hl-path">/api/checkout/session</span>.' },
  { t: "11:42:18", lvl: "tool", msg: 'Read(<span class="hl-path">src/checkout/api.ts</span>) <span class="hl-dim">— 248 lines</span>' },
  { t: "11:42:21", lvl: "tool", msg: 'Grep(<span class="hl-quote">"checkout/session"</span>, glob=<span class="hl-quote">"src/**"</span>) <span class="hl-dim">— 14 matches</span>' },
  { t: "11:42:23", lvl: "claude", msg: 'I see <span class="hl-num">14</span> call sites. Three are inside <span class="hl-path">PaymentStep.tsx</span>. The schema change is breaking — <span class="hl-kw">total</span> moves from integer→decimal. Need to update parsing on the client.' },
  { t: "11:42:26", lvl: "tool", msg: 'Edit(<span class="hl-path">src/checkout/api.ts</span>) <span class="hl-dim">— +12 −4</span>' },
  { t: "11:42:28", lvl: "tool", msg: 'Edit(<span class="hl-path">src/checkout/types.ts</span>) <span class="hl-dim">— +6 −2</span>' },
  { t: "11:42:30", lvl: "info", msg: 'Outbox → <span class="hl-kw">test-writer</span>: <span class="hl-quote">"Need fixtures: promo_code valid_active, valid_expired, invalid_format"</span>' },
  { t: "11:42:31", lvl: "tool", msg: 'Bash(<span class="hl-quote">pnpm typecheck</span>) <span class="hl-dim">— exit 0 in 2.4s</span>' },
  { t: "11:42:34", lvl: "tool", msg: 'Bash(<span class="hl-quote">pnpm test --filter checkout</span>) <span class="hl-dim">— 47 passed, 0 failed in 8.1s</span>' },
  { t: "11:42:35", lvl: "warn", msg: 'TypeScript: implicit any in <span class="hl-path">PaymentStep.tsx:142</span> <span class="hl-dim">(deferred)</span>' },
  { t: "11:42:38", lvl: "claude", msg: 'Schema migration applied client-side. Tests green. Now addressing the <span class="hl-kw">a11y</span> report from <span class="hl-kw">ui-reviewer</span>.' },
  { t: "11:42:40", lvl: "tool", msg: 'Read(<span class="hl-path">src/checkout/PaymentStep.tsx</span>) <span class="hl-dim">— 312 lines</span>' },
  { t: "11:42:43", lvl: "tool", msg: 'Edit(<span class="hl-path">src/checkout/PaymentStep.tsx</span>) <span class="hl-dim">— +18 −6 (3 a11y fixes)</span>' },
  { t: "11:42:45", lvl: "info", msg: 'Outbox → <span class="hl-kw">ui-reviewer</span>: <span class="hl-quote">"PaymentStep a11y fixes pushed to fix/payment-step-a11y"</span>' },
  { t: "11:42:46", lvl: "tool", msg: 'Bash(<span class="hl-quote">git commit -am "fix(checkout): a11y on PaymentStep"</span>) <span class="hl-dim">— 1 file changed</span>' },
];

const ACTIVITY = [
  { kind: "accent", body: "test-writer sent fixtures for promo flow", time: "1m ago" },
  { kind: "ok", body: "frontend-refactor pushed fix/payment-step-a11y", time: "3m ago" },
  { kind: "ok", body: "backend-api deployed schema v34 to staging", time: "12m ago" },
  { kind: "warn", body: "perf-investigator hit rate limit (anthropic-api)", time: "27m ago" },
  { kind: "err", body: "perf-investigator container exited (1)", time: "27m ago" },
  { kind: "default", body: "release-pilot scheduled v3.4.0 freeze", time: "3h ago" },
];

window.AGENTS = AGENTS;
window.INBOX = INBOX;
window.LOG_SEED = LOG_SEED;
window.ACTIVITY = ACTIVITY;
