name: DB Push

on:
  workflow_dispatch:

jobs:
  db-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install -g prisma
      - run: prisma db push --schema=prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
